#Lab 2

# New Section

In [ ]:
import numpy as np
import pandas as pd
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split 
from keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential, Model, load_model, save_model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense, Activation, Dropout, Input, Masking, TimeDistributed, LSTM, Conv1D, Embedding
from tensorflow.keras.layers import GRU, Bidirectional, BatchNormalization, Reshape
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.layers import Reshape, Dropout, Dense,Multiply, Dot, Concatenate,Embedding
from tensorflow.keras import optimizers
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
telecom_cust=pd.read_csv('Telco-Customer-Churn.csv') 
telecom_cust.shape, telecom_cust

((7043, 21),
       customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
 0     7590-VHVEG  Female              0  ...          29.85        29.85     No
 1     5575-GNVDE    Male              0  ...          56.95       1889.5     No
 2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
 3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
 4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
 ...          ...     ...            ...  ...            ...          ...    ...
 7038  6840-RESVB    Male              0  ...          84.80       1990.5     No
 7039  2234-XADUH  Female              0  ...         103.20       7362.9     No
 7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
 7041  8361-LTMKD    Male              1  ...          74.40        306.6    Yes
 7042  3186-AJIEK    Male              0  ...         105.65       6844.5     No

 [7043 rows x 21 columns])

In [ ]:
telecom_cust['TotalCharges'] = pd.to_numeric(telecom_cust['TotalCharges'],errors='coerce') 
telecom_cust.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [ ]:
telecom_cust = telecom_cust.drop(columns = ['customerID']) 
telecom_cust

      gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
0     Female              0     Yes  ...          29.85         29.85    No
1       Male              0      No  ...          56.95       1889.50    No
2       Male              0      No  ...          53.85        108.15   Yes
3       Male              0      No  ...          42.30       1840.75    No
4     Female              0      No  ...          70.70        151.65   Yes
...      ...            ...     ...  ...            ...           ...   ...
7038    Male              0     Yes  ...          84.80       1990.50    No
7039  Female              0     Yes  ...         103.20       7362.90    No
7040  Female              0     Yes  ...          29.60        346.45    No
7041    Male              1     Yes  ...          74.40        306.60   Yes
7042    Male              0      No  ...         105.65       6844.50    No

[7043 rows x 20 columns]

In [ ]:
telecom_cust.dropna(inplace = True)

In [ ]:
telecom_cust['Churn'].replace(to_replace='Yes', value=1, inplace=True) 
telecom_cust['Churn'].replace(to_replace='No', value=0, inplace=True)

In [ ]:
telecom_cust_y = telecom_cust['Churn'] 
telecom_cust = telecom_cust.drop(columns = ['Churn']) 
telecom_cust

      gender  SeniorCitizen  ... MonthlyCharges TotalCharges
0     Female              0  ...          29.85        29.85
1       Male              0  ...          56.95      1889.50
2       Male              0  ...          53.85       108.15
3       Male              0  ...          42.30      1840.75
4     Female              0  ...          70.70       151.65
...      ...            ...  ...            ...          ...
7038    Male              0  ...          84.80      1990.50
7039  Female              0  ...         103.20      7362.90
7040  Female              0  ...          29.60       346.45
7041    Male              1  ...          74.40       306.60
7042    Male              0  ...         105.65      6844.50

[7032 rows x 19 columns]

In [ ]:
telecom_cust = pd.get_dummies(telecom_cust) 
telecom_cust

      SeniorCitizen  ...  PaymentMethod_Mailed check
0                 0  ...                           0
1                 0  ...                           1
2                 0  ...                           1
3                 0  ...                           0
4                 0  ...                           0
...             ...  ...                         ...
7038              0  ...                           1
7039              0  ...                           0
7040              0  ...                           0
7041              1  ...                           1
7042              0  ...                           0

[7032 rows x 45 columns]

In [ ]:
scaler = MinMaxScaler(feature_range = (0,1)) 
scaler.fit(telecom_cust) 
telecom_cust = pd.DataFrame(scaler.transform(telecom_cust)) 
telecom_cust

       0         1         2         3    4    5   ...   39   40   41   42   43   44
0     0.0  0.000000  0.115423  0.001275  1.0  0.0  ...  0.0  1.0  0.0  0.0  1.0  0.0
1     0.0  0.464789  0.385075  0.215867  0.0  1.0  ...  1.0  0.0  0.0  0.0  0.0  1.0
2     0.0  0.014085  0.354229  0.010310  0.0  1.0  ...  0.0  1.0  0.0  0.0  0.0  1.0
3     0.0  0.619718  0.239303  0.210241  0.0  1.0  ...  1.0  0.0  1.0  0.0  0.0  0.0
4     0.0  0.014085  0.521891  0.015330  1.0  0.0  ...  0.0  1.0  0.0  0.0  1.0  0.0
...   ...       ...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
7027  0.0  0.323944  0.662189  0.227521  0.0  1.0  ...  0.0  1.0  0.0  0.0  0.0  1.0
7028  0.0  1.000000  0.845274  0.847461  1.0  0.0  ...  0.0  1.0  0.0  1.0  0.0  0.0
7029  0.0  0.140845  0.112935  0.037809  1.0  0.0  ...  0.0  1.0  0.0  0.0  1.0  0.0
7030  1.0  0.042254  0.558706  0.033210  0.0  1.0  ...  0.0  1.0  0.0  0.0  0.0  1.0
7031  0.0  0.915493  0.869652  0.787641  0.0  1.0  ...  0.0  1.0  1.0  0.0  0.0  0.0

[7032 rows x 45 columns]

In [ ]:
telecom_cust_x = telecom_cust 
x_train, x_test, y_train, y_test = train_test_split(telecom_cust_x, telecom_cust_y, test_size=0.2) 
print (x_train.shape, y_train.shape) 
print (x_test.shape, y_test.shape)

(5625, 45) (5625,)
(1407, 45) (1407,)

In [ ]:
input_size=x_train.shape[1] 
input_size

45

In [ ]:
model = Sequential()
model.add(Dense(64, input_dim= input_size , kernel_initializer='uniform', activation='relu'))
model.add(Dense(32, kernel_initializer='uniform', activation='relu'))
model.add(Dense(16, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='Adagrad', metrics=['accuracy']) 
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 64)                2944
_________________________________________________________________
dense_1 (Dense)              (None, 32)                2080
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17
=================================================================
Total params: 5,569
Trainable params: 5,569
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.fit(x_train, y_train, epochs=200, batch_size=10, verbose=2)

Epoch 1/200
563/563 - 1s - loss: 0.6874 - accuracy: 0.7307
Epoch 2/200
563/563 - 0s - loss: 0.6821 - accuracy: 0.7307
Epoch 3/200
563/563 - 1s - loss: 0.6785 - accuracy: 0.7307
Epoch 4/200
563/563 - 0s - loss: 0.6752 - accuracy: 0.7307
Epoch 5/200
563/563 - 1s - loss: 0.6721 - accuracy: 0.7307
Epoch 6/200
563/563 - 1s - loss: 0.6689 - accuracy: 0.7307
Epoch 7/200
563/563 - 1s - loss: 0.6656 - accuracy: 0.7307
Epoch 8/200
563/563 - 1s - loss: 0.6621 - accuracy: 0.7307
Epoch 9/200
563/563 - 1s - loss: 0.6585 - accuracy: 0.7307
Epoch 10/200
563/563 - 1s - loss: 0.6549 - accuracy: 0.7307
Epoch 11/200
563/563 - 1s - loss: 0.6513 - accuracy: 0.7307
Epoch 12/200
563/563 - 1s - loss: 0.6477 - accuracy: 0.7307
Epoch 13/200
563/563 - 1s - loss: 0.6441 - accuracy: 0.7307
Epoch 14/200
563/563 - 1s - loss: 0.6405 - accuracy: 0.7307
Epoch 15/200
563/563 - 1s - loss: 0.6370 - accuracy: 0.7307
Epoch 16/200
563/563 - 1s - loss: 0.6334 - accuracy: 0.7307
Epoch 17/200
563/563 - 1s - loss: 0.6297 - accuracy: 0.7307
Epoch 18/200
563/563 - 1s - loss: 0.6260 - accuracy: 0.7307
Epoch 19/200
563/563 - 1s - loss: 0.6220 - accuracy: 0.7307
Epoch 20/200
563/563 - 0s - loss: 0.6177 - accuracy: 0.7307
Epoch 21/200
563/563 - 0s - loss: 0.6130 - accuracy: 0.7307
Epoch 22/200
563/563 - 1s - loss: 0.6076 - accuracy: 0.7307
Epoch 23/200
563/563 - 1s - loss: 0.6014 - accuracy: 0.7307
Epoch 24/200
563/563 - 0s - loss: 0.5942 - accuracy: 0.7307
Epoch 25/200
563/563 - 0s - loss: 0.5860 - accuracy: 0.7307
Epoch 26/200
563/563 - 1s - loss: 0.5767 - accuracy: 0.7307
Epoch 27/200
563/563 - 1s - loss: 0.5667 - accuracy: 0.7307
Epoch 28/200
563/563 - 0s - loss: 0.5563 - accuracy: 0.7307
Epoch 29/200
563/563 - 1s - loss: 0.5458 - accuracy: 0.7307
Epoch 30/200
563/563 - 0s - loss: 0.5355 - accuracy: 0.7307
Epoch 31/200
563/563 - 1s - loss: 0.5259 - accuracy: 0.7307
Epoch 32/200
563/563 - 0s - loss: 0.5172 - accuracy: 0.7307
Epoch 33/200
563/563 - 0s - loss: 0.5095 - accuracy: 0.7307
Epoch 34/200
563/563 - 0s - loss: 0.5026 - accuracy: 0.7307
Epoch 35/200
563/563 - 0s - loss: 0.4962 - accuracy: 0.7307
Epoch 36/200
563/563 - 0s - loss: 0.4905 - accuracy: 0.7307
Epoch 37/200
563/563 - 0s - loss: 0.4857 - accuracy: 0.7307
Epoch 38/200
563/563 - 0s - loss: 0.4818 - accuracy: 0.7307
Epoch 39/200
563/563 - 1s - loss: 0.4786 - accuracy: 0.7307
Epoch 40/200
563/563 - 0s - loss: 0.4763 - accuracy: 0.7307
Epoch 41/200
563/563 - 0s - loss: 0.4743 - accuracy: 0.7307
Epoch 42/200
563/563 - 0s - loss: 0.4727 - accuracy: 0.7307
Epoch 43/200
563/563 - 0s - loss: 0.4712 - accuracy: 0.7307
Epoch 44/200
563/563 - 0s - loss: 0.4699 - accuracy: 0.7307
Epoch 45/200
563/563 - 1s - loss: 0.4687 - accuracy: 0.7307
Epoch 46/200
563/563 - 0s - loss: 0.4675 - accuracy: 0.7307
Epoch 47/200
563/563 - 1s - loss: 0.4664 - accuracy: 0.7307
Epoch 48/200
563/563 - 0s - loss: 0.4653 - accuracy: 0.7307
Epoch 49/200
563/563 - 0s - loss: 0.4642 - accuracy: 0.7307
Epoch 50/200
563/563 - 0s - loss: 0.4631 - accuracy: 0.7307
Epoch 51/200
563/563 - 1s - loss: 0.4620 - accuracy: 0.7307
Epoch 52/200
563/563 - 1s - loss: 0.4609 - accuracy: 0.7307
Epoch 53/200
563/563 - 0s - loss: 0.4598 - accuracy: 0.7307
Epoch 54/200
563/563 - 0s - loss: 0.4587 - accuracy: 0.7307
Epoch 55/200
563/563 - 0s - loss: 0.4575 - accuracy: 0.7307
Epoch 56/200
563/563 - 0s - loss: 0.4563 - accuracy: 0.7307
Epoch 57/200
563/563 - 1s - loss: 0.4551 - accuracy: 0.7307
Epoch 58/200
563/563 - 0s - loss: 0.4539 - accuracy: 0.7307
Epoch 59/200
563/563 - 0s - loss: 0.4526 - accuracy: 0.7307
Epoch 60/200
563/563 - 0s - loss: 0.4514 - accuracy: 0.7307
Epoch 61/200
563/563 - 0s - loss: 0.4503 - accuracy: 0.7307
Epoch 62/200
563/563 - 1s - loss: 0.4493 - accuracy: 0.7307
Epoch 63/200
563/563 - 0s - loss: 0.4486 - accuracy: 0.7307
Epoch 64/200
563/563 - 1s - loss: 0.4479 - accuracy: 0.7307
Epoch 65/200
563/563 - 0s - loss: 0.4473 - accuracy: 0.7307
Epoch 66/200
563/563 - 1s - loss: 0.4468 - accuracy: 0.7307
Epoch 67/200
563/563 - 0s - loss: 0.4464 - accuracy: 0.7307
Epoch 68/200
563/563 - 1s - loss: 0.4460 - accuracy: 0.7307
Epoch 69/200
563/563 - 0s - loss: 0.4456 - accuracy: 0.7307
Epoch 70/200
563/563 - 0s - loss: 0.4452 - accuracy: 0.7307
Epoch 71/200
563/563 - 1s - loss: 0.4449 - accuracy: 0.7307
Epoch 72/200
563/563 - 0s - loss: 0.4446 - accuracy: 0.7307
Epoch 73/200
563/563 - 0s - loss: 0.4442 - accuracy: 0.7307
Epoch 74/200
563/563 - 1s - loss: 0.4439 - accuracy: 0.7307
Epoch 75/200
563/563 - 0s - loss: 0.4437 - accuracy: 0.7307
Epoch 76/200
563/563 - 0s - loss: 0.4434 - accuracy: 0.7307
Epoch 77/200
563/563 - 0s - loss: 0.4431 - accuracy: 0.7307
Epoch 78/200
563/563 - 0s - loss: 0.4428 - accuracy: 0.7307
Epoch 79/200
563/563 - 1s - loss: 0.4426 - accuracy: 0.7307
Epoch 80/200
563/563 - 0s - loss: 0.4423 - accuracy: 0.7307
Epoch 81/200
563/563 - 0s - loss: 0.4420 - accuracy: 0.7307
Epoch 82/200
563/563 - 1s - loss: 0.4417 - accuracy: 0.7307
Epoch 83/200
563/563 - 0s - loss: 0.4415 - accuracy: 0.7307
Epoch 84/200
563/563 - 1s - loss: 0.4412 - accuracy: 0.7307
Epoch 85/200
563/563 - 1s - loss: 0.4409 - accuracy: 0.7307
Epoch 86/200
563/563 - 0s - loss: 0.4406 - accuracy: 0.7307
Epoch 87/200
563/563 - 1s - loss: 0.4404 - accuracy: 0.7307
Epoch 88/200
563/563 - 0s - loss: 0.4401 - accuracy: 0.7307
Epoch 89/200
563/563 - 0s - loss: 0.4398 - accuracy: 0.7307
Epoch 90/200
563/563 - 0s - loss: 0.4396 - accuracy: 0.7307
Epoch 91/200
563/563 - 0s - loss: 0.4393 - accuracy: 0.7307
Epoch 92/200
563/563 - 1s - loss: 0.4390 - accuracy: 0.7308
Epoch 93/200
563/563 - 0s - loss: 0.4387 - accuracy: 0.7381
Epoch 94/200
563/563 - 0s - loss: 0.4385 - accuracy: 0.7678
Epoch 95/200
563/563 - 0s - loss: 0.4382 - accuracy: 0.7858
Epoch 96/200
563/563 - 0s - loss: 0.4379 - accuracy: 0.7925
Epoch 97/200
563/563 - 0s - loss: 0.4377 - accuracy: 0.7956
Epoch 98/200
563/563 - 0s - loss: 0.4374 - accuracy: 0.7964
Epoch 99/200
563/563 - 0s - loss: 0.4371 - accuracy: 0.7972
Epoch 100/200
563/563 - 0s - loss: 0.4369 - accuracy: 0.7982
Epoch 101/200
563/563 - 0s - loss: 0.4366 - accuracy: 0.7973
Epoch 102/200
563/563 - 0s - loss: 0.4363 - accuracy: 0.7980
Epoch 103/200
563/563 - 1s - loss: 0.4361 - accuracy: 0.7979
Epoch 104/200
563/563 - 0s - loss: 0.4358 - accuracy: 0.7979
Epoch 105/200
563/563 - 1s - loss: 0.4356 - accuracy: 0.7984
Epoch 106/200
563/563 - 0s - loss: 0.4353 - accuracy: 0.7980
Epoch 107/200
563/563 - 0s - loss: 0.4351 - accuracy: 0.7984
Epoch 108/200
563/563 - 0s - loss: 0.4348 - accuracy: 0.7982
Epoch 109/200
563/563 - 1s - loss: 0.4346 - accuracy: 0.7986
Epoch 110/200
563/563 - 1s - loss: 0.4343 - accuracy: 0.7980
Epoch 111/200
563/563 - 1s - loss: 0.4341 - accuracy: 0.7993
Epoch 112/200
563/563 - 1s - loss: 0.4338 - accuracy: 0.7988
Epoch 113/200
563/563 - 1s - loss: 0.4336 - accuracy: 0.7991
Epoch 114/200
563/563 - 1s - loss: 0.4334 - accuracy: 0.7988
Epoch 115/200
563/563 - 1s - loss: 0.4331 - accuracy: 0.7989
Epoch 116/200
563/563 - 0s - loss: 0.4329 - accuracy: 0.7989
Epoch 117/200
563/563 - 1s - loss: 0.4327 - accuracy: 0.7988
Epoch 118/200
563/563 - 1s - loss: 0.4324 - accuracy: 0.7986
Epoch 119/200
563/563 - 1s - loss: 0.4322 - accuracy: 0.7995
Epoch 120/200
563/563 - 1s - loss: 0.4320 - accuracy: 0.7993
Epoch 121/200
563/563 - 1s - loss: 0.4318 - accuracy: 0.7989
Epoch 122/200
563/563 - 1s - loss: 0.4315 - accuracy: 0.7986
Epoch 123/200
563/563 - 1s - loss: 0.4313 - accuracy: 0.7995
Epoch 124/200
563/563 - 1s - loss: 0.4311 - accuracy: 0.7991
Epoch 125/200
563/563 - 1s - loss: 0.4309 - accuracy: 0.7993
Epoch 126/200
563/563 - 1s - loss: 0.4307 - accuracy: 0.7996
Epoch 127/200
563/563 - 1s - loss: 0.4305 - accuracy: 0.7988
Epoch 128/200
563/563 - 1s - loss: 0.4303 - accuracy: 0.7993
Epoch 129/200
563/563 - 1s - loss: 0.4301 - accuracy: 0.7989
Epoch 130/200
563/563 - 1s - loss: 0.4299 - accuracy: 0.7991
Epoch 131/200
563/563 - 1s - loss: 0.4297 - accuracy: 0.8002
Epoch 132/200
563/563 - 1s - loss: 0.4295 - accuracy: 0.7998
Epoch 133/200
563/563 - 1s - loss: 0.4293 - accuracy: 0.7993
Epoch 134/200
563/563 - 1s - loss: 0.4292 - accuracy: 0.7995
Epoch 135/200
563/563 - 0s - loss: 0.4290 - accuracy: 0.7991
Epoch 136/200
563/563 - 1s - loss: 0.4288 - accuracy: 0.7998
Epoch 137/200
563/563 - 1s - loss: 0.4286 - accuracy: 0.8004
Epoch 138/200
563/563 - 1s - loss: 0.4285 - accuracy: 0.8005
Epoch 139/200
563/563 - 1s - loss: 0.4283 - accuracy: 0.8005
Epoch 140/200
563/563 - 1s - loss: 0.4281 - accuracy: 0.8005
Epoch 141/200
563/563 - 0s - loss: 0.4280 - accuracy: 0.8000
Epoch 142/200
563/563 - 1s - loss: 0.4278 - accuracy: 0.8002
Epoch 143/200
563/563 - 1s - loss: 0.4277 - accuracy: 0.8004
Epoch 144/200
563/563 - 1s - loss: 0.4275 - accuracy: 0.8011
Epoch 145/200
563/563 - 0s - loss: 0.4274 - accuracy: 0.8007
Epoch 146/200
563/563 - 0s - loss: 0.4272 - accuracy: 0.8005
Epoch 147/200
563/563 - 0s - loss: 0.4271 - accuracy: 0.8004
Epoch 148/200
563/563 - 0s - loss: 0.4269 - accuracy: 0.8009
Epoch 149/200
563/563 - 1s - loss: 0.4268 - accuracy: 0.8009
Epoch 150/200
563/563 - 0s - loss: 0.4267 - accuracy: 0.8005
Epoch 151/200
563/563 - 0s - loss: 0.4265 - accuracy: 0.8005
Epoch 152/200
563/563 - 0s - loss: 0.4264 - accuracy: 0.8007
Epoch 153/200
563/563 - 0s - loss: 0.4263 - accuracy: 0.8007
Epoch 154/200
563/563 - 0s - loss: 0.4261 - accuracy: 0.8004
Epoch 155/200
563/563 - 0s - loss: 0.4260 - accuracy: 0.8011
Epoch 156/200
563/563 - 0s - loss: 0.4259 - accuracy: 0.8005
Epoch 157/200
563/563 - 0s - loss: 0.4258 - accuracy: 0.8011
Epoch 158/200
563/563 - 0s - loss: 0.4257 - accuracy: 0.8011
Epoch 159/200
563/563 - 0s - loss: 0.4255 - accuracy: 0.8000
Epoch 160/200
563/563 - 0s - loss: 0.4254 - accuracy: 0.8007
Epoch 161/200
563/563 - 0s - loss: 0.4253 - accuracy: 0.8005
Epoch 162/200
563/563 - 0s - loss: 0.4252 - accuracy: 0.8005
Epoch 163/200
563/563 - 0s - loss: 0.4251 - accuracy: 0.8012
Epoch 164/200
563/563 - 1s - loss: 0.4250 - accuracy: 0.8011
Epoch 165/200
563/563 - 0s - loss: 0.4249 - accuracy: 0.8009
Epoch 166/200
563/563 - 0s - loss: 0.4248 - accuracy: 0.8005
Epoch 167/200
563/563 - 1s - loss: 0.4246 - accuracy: 0.8002
Epoch 168/200
563/563 - 0s - loss: 0.4245 - accuracy: 0.8011
Epoch 169/200
563/563 - 0s - loss: 0.4244 - accuracy: 0.8005
Epoch 170/200
563/563 - 1s - loss: 0.4243 - accuracy: 0.8009
Epoch 171/200
563/563 - 1s - loss: 0.4243 - accuracy: 0.8007
Epoch 172/200
563/563 - 0s - loss: 0.4242 - accuracy: 0.8012
Epoch 173/200
563/563 - 0s - loss: 0.4240 - accuracy: 0.8014
Epoch 174/200
563/563 - 1s - loss: 0.4239 - accuracy: 0.8014
Epoch 175/200
563/563 - 1s - loss: 0.4239 - accuracy: 0.8007
Epoch 176/200
563/563 - 0s - loss: 0.4238 - accuracy: 0.8007
Epoch 177/200
563/563 - 1s - loss: 0.4237 - accuracy: 0.8012
Epoch 178/200
563/563 - 1s - loss: 0.4236 - accuracy: 0.8012
Epoch 179/200
563/563 - 0s - loss: 0.4235 - accuracy: 0.8004
Epoch 180/200
563/563 - 1s - loss: 0.4234 - accuracy: 0.8009
Epoch 181/200
563/563 - 0s - loss: 0.4233 - accuracy: 0.8012
Epoch 182/200
563/563 - 1s - loss: 0.4233 - accuracy: 0.8018
Epoch 183/200
563/563 - 0s - loss: 0.4232 - accuracy: 0.8011
Epoch 184/200
563/563 - 0s - loss: 0.4231 - accuracy: 0.8011
Epoch 185/200
563/563 - 0s - loss: 0.4230 - accuracy: 0.8012
Epoch 186/200
563/563 - 0s - loss: 0.4229 - accuracy: 0.8011
Epoch 187/200
563/563 - 1s - loss: 0.4229 - accuracy: 0.8011
Epoch 188/200
563/563 - 1s - loss: 0.4228 - accuracy: 0.8009
Epoch 189/200
563/563 - 1s - loss: 0.4227 - accuracy: 0.8011
Epoch 190/200
563/563 - 1s - loss: 0.4226 - accuracy: 0.8011
Epoch 191/200
563/563 - 1s - loss: 0.4226 - accuracy: 0.8005
Epoch 192/200
563/563 - 0s - loss: 0.4225 - accuracy: 0.8011
Epoch 193/200
563/563 - 1s - loss: 0.4224 - accuracy: 0.8011
Epoch 194/200
563/563 - 0s - loss: 0.4223 - accuracy: 0.8011
Epoch 195/200
563/563 - 1s - loss: 0.4223 - accuracy: 0.8009
Epoch 196/200
563/563 - 1s - loss: 0.4222 - accuracy: 0.8016
Epoch 197/200
563/563 - 1s - loss: 0.4221 - accuracy: 0.8009
Epoch 198/200
563/563 - 1s - loss: 0.4221 - accuracy: 0.8014
Epoch 199/200
563/563 - 1s - loss: 0.4220 - accuracy: 0.8012
Epoch 200/200
563/563 - 1s - loss: 0.4220 - accuracy: 0.8012

In [ ]:
  loss, accuracy = model.evaluate(x_train, y_train) 
print('Accuracy % = ', round(accuracy*100,2))

176/176 [==============================] - 0s 1ms/step - loss: 0.4218 - accuracy: 0.8009
Accuracy % =  80.09

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test) 
print('Accuracy % = ', round(accuracy*100,2))

44/44 [==============================] - 0s 1ms/step - loss: 0.4221 - accuracy: 0.7953
Accuracy % =  79.53

In [ ]:
model.save('telco.h5')

In [ ]:
predictions = model.predict(x_test)

In [ ]:

rounded = [round(x[0]) for x in predictions] 
print(rounded)

[0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1]